import mongoose, { Schema, Types } from "mongoose";

// 1. Updated Interface
interface Ichannel {
  userId: Types.ObjectId;
  channelName: string;
  handleName: string;
  profilePicture: string;
  links: {
    _id: Types.ObjectId;
    logo?: string | null;
    name?: string | null;
    url?: string | null;
  }[];
  state: "active" | "suspended";
  bannerImage: string;
  description: string;
  isChannelSetup: boolean;
  stats: {
    subscriberCount: number; // Changed to number for consistency
    videoCount: number;
  };
  homeSections: {
    sectionType: "trailer" | "shorts" | "videos" | "playlists" | "posts";
    title?: string;
    layout: "horizontal" | "vertical";
    // Stores IDs of Videos, Posts, or Playlists
    contentReferences: Types.ObjectId[];
    // Tells Mongoose which model to use for population (Video, Post, or Playlist)
    contentType: "Video" | "Post" | "Playlist";
    isAutoGenerated: boolean;
  }[];
  createdAt: Date;
  updatedAt: Date;
}

const channelSchema = new Schema<Ichannel>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true },
    channelName: { type: String, required: true },
    handleName: { type: String, required: true, unique: true, trim: true },
    profilePicture: { type: String, default: null },
    bannerImage: { type: String, default: null },
    description: { type: String, default: null },
    state: { type: String, enum: ["active", "suspended"], default: "active" },

    links: {
      type: [
        {
          _id: { type: Schema.Types.ObjectId, auto: true },
          logo: { type: String, default: null },
          name: { type: String, default: null },
          url: { type: String, default: null },
        },
      ],
      default: [],
      required: false,
    },

    homeSections: {
      type: [
        {
          sectionType: {
            type: String,
            enum: ["trailer", "shorts", "videos", "playlists", "posts"],
            required: true,
          },
          title: { type: String, default: null },
          layout: {
            type: String,
            enum: ["horizontal", "vertical"],
            default: "horizontal",
          },
          isAutoGenerated: { type: Boolean, default: false },

          // This array holds the IDs
          contentReferences: [
            {
              type: Schema.Types.ObjectId,
              refPath: "homeSections.contentType", // Dynamic Reference!
            },
          ],

          contentType: {
            type: String,
            required: true,
            enum: ["Video", "Post", "Playlist", "Posts", "Shorts"],
            default: "Video",
          },
        },
      ],
      validate: {
        validator: function (val: any[]) {
          return val.length <= 9;
        },
        message: "A channel can have a maximum of 12 featured sections.",
      },

      default: [],
      required: false,
    },

    isChannelSetup: { type: Boolean, default: false },
    stats: {
      subscriberCount: { type: Number, default: 0 },
      videoCount: { type: Number, default: 0 },
    },
  },
  { timestamps: true },
);

channelSchema.index({ handleName: 1, createdAt: -1 });

export const Channel = mongoose.model<Ichannel>("Channel", channelSchema);
